export const Categories = [
  {
    id: 10,
    title: 'صاروخ',
    slug: 'صاروخ',
    parentId: null,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 12,
    title: 'اكسسوارات',
    slug: 'اكسسوارات',
    parentId: null,
    order: 21,
    img: 'http://etoolsshop.com/uploads/images/category/اطقم.png',
    active: 1,
  },
  {
    id: 13,
    title: 'بلاور',
    slug: 'بلاور',
    parentId: null,
    order: 5,
    img: 'http://etoolsshop.com/uploads/images/category/بلاور.png',
    active: 1,
  },
  {
    id: 22,
    title: 'اجهزة قياس وتحديد مستويات بالليزر ',
    slug: 'اجهزة-قياس-وتحديد-مستويات-بالليزر-',
    parentId: null,
    order: 4,
    img:
      'http://etoolsshop.com/uploads/images/category/laser%20destance%20meter1.jpg',
    active: 1,
  },
  {
    id: 16,
    title: 'كاشف ',
    slug: 'كاشف-',
    parentId: 22,
    order: 6,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 17,
    title: 'شنيور',
    slug: 'شنيور',
    parentId: null,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/شنيور%20دقاق.png',
    active: 1,
  },
  {
    id: 18,
    title: 'ادوات ومعدات حدائق',
    slug: 'ادوات-ومعدات-حدائق',
    parentId: null,
    order: 14,
    img: 'http://etoolsshop.com/uploads/images/category/منشار%20الحدائق.png',
    active: 1,
  },
  {
    id: 19,
    title: 'شاكوش التخريم والتكسير (هيلتي)',
    slug: 'شاكوش-التخريم-والتكسير-(هيلتي)',
    parentId: null,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/Rotary%20Hammer.jpg',
    active: 1,
  },
  {
    id: 20,
    title: 'مسدس تسخين',
    slug: 'مسدس-تسخين',
    parentId: null,
    order: 13,
    img: 'http://etoolsshop.com/uploads/images/category/مسدس%20تسخين.png',
    active: 1,
  },

  {
    id: 24,
    title: 'اجهزه متعددة الاستخدامات',
    slug: 'اجهزه-متعددة-الاستخدامات',
    parentId: null,
    order: 16,
    img:
      'http://etoolsshop.com/uploads/images/category/ترددى%20متعدد%20الاستخدامات.png',
    active: 1,
  },
  {
    id: 25,
    title: 'رشاشات دهانات',
    slug: 'رشاشات-دهانات',
    parentId: null,
    order: 17,
    img: 'http://etoolsshop.com/uploads/images/category/رشاشات%20دهانات.png',
    active: 1,
  },
  {
    id: 28,
    title: 'منشار كهربائي',
    slug: 'منشار-كهربائي',
    parentId: null,
    order: 6,
    img:
      'http://etoolsshop.com/uploads/images/category/منشار%20ترددى%20أمامى.png',
    active: 1,
  },
  {
    id: 131,
    title: 'اسطوانات قطعيه',
    slug: 'اسطوانات-قطعيه',
    parentId: null,
    order: 10,
    img:
      'http://etoolsshop.com/uploads/images/category/CIRCULAR%20SAW%20DISC%201.jpg',
    active: 1,
  },
  {
    id: 50,
    title: 'اسطوانات صينية ماكينات ',
    slug: 'اسطوانات-صينية-ماكينات-',
    parentId: 131,
    order: 4,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 53,
    title: 'اسطوانات الماظة',
    slug: 'اسطوانات-الماظة',
    parentId: 131,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 54,
    title: 'اجهزه متعدده الاستخدامات-بالبطاريه',
    slug: 'اجهزه-متعدده-الاستخدامات-بالبطاريه',
    parentId: 24,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 55,
    title: 'اجهزه متعدده الاستخدامات-عاده',
    slug: 'اجهزه-متعدده-الاستخدامات-عاده',
    parentId: 24,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/saf7a-beda.jpg',
    active: 1,
  },
  {
    id: 63,
    title: 'شنيور كور',
    slug: 'شنيور-كور',
    parentId: 17,
    order: 4,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 67,
    title: 'شنيور فك وربط كهرباء',
    slug: 'شنيور-فك-وربط-كهرباء',
    parentId: 17,
    order: 5,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 69,
    title: 'قفازات',
    slug: 'قفازات',
    parentId: 18,
    order: 5,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 73,
    title: 'منشار شجر',
    slug: 'منشار-شجر',
    parentId: 18,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 76,
    title: 'ميزان شيرب ليزر',
    slug: 'ميزان-شيرب-ليزر',
    parentId: 22,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/WHITE%20PAPER.jpg',
    active: 1,
  },
  {
    id: 78,
    title: 'زاويه ديجيتال',
    slug: 'زاويه-ديجيتال',
    parentId: 22,
    order: 5,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 79,
    title: 'متر قياس ليزر',
    slug: 'متر-قياس-ليزر',
    parentId: 22,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/WHITE%20PAPER.jpg',
    active: 1,
  },
  {
    id: 82,
    title: 'منشار اركيت',
    slug: 'منشار-اركيت',
    parentId: 28,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/WHITE%20PAPER.jpg',
    active: 1,
  },
  {
    id: 84,
    title: ' بنط ',
    slug: '-بنط-',
    parentId: null,
    order: 23,
    img: 'http://etoolsshop.com/uploads/images/category/بنط.png',
    active: 1,
  },
  {
    id: 87,
    title: 'دباسه',
    slug: 'دباسه',
    parentId: null,
    order: 18,
    img: 'http://etoolsshop.com/uploads/images/category/دباسة.png',
    active: 1,
  },
  {
    id: 88,
    title: 'شنيور زاوية ',
    slug: 'شنيور-زاوية-',
    parentId: 17,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 90,
    title: 'صاروخ تلميع',
    slug: 'صاروخ-تلميع',
    parentId: 10,
    order: 7,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 91,
    title: 'صاروخ اسطمبات',
    slug: 'صاروخ-اسطمبات',
    parentId: 10,
    order: 8,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 92,
    title: 'صاروخ شق في الخرسانه',
    slug: 'صاروخ-شق-في-الخرسانه',
    parentId: 10,
    order: 8,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 93,
    title: 'شنيور يمين وشمال ودقاق',
    slug: 'شنيور-يمين-وشمال-ودقاق',
    parentId: 17,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/WHITE%20PAPER.jpg',
    active: 1,
  },
  {
    id: 94,
    title: 'شاكوش تخريم وتكسير خفيف',
    slug: 'شاكوش-تخريم-وتكسير-خفيف',
    parentId: 19,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 95,
    title: 'شاكوش تخريم وتكسير ثقيل',
    slug: 'شاكوش-تخريم-وتكسير-ثقيل',
    parentId: 19,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 96,
    title: 'شاكوش تكسير',
    slug: 'شاكوش-تكسير',
    parentId: 19,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 97,
    title: 'شاكوش بالبطاريه',
    slug: 'شاكوش-بالبطاريه',
    parentId: 19,
    order: 4,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 98,
    title: 'شنيور ومفك شحن بالبطاريه',
    slug: 'شنيور-ومفك-شحن-بالبطاريه',
    parentId: null,
    order: 7,
    img: 'http://etoolsshop.com/uploads/images/category/شنيور بطارية.png',
    active: 1,
  },
  {
    id: 100,
    title: 'شنيور ومفك (شحن بطارية)',
    slug: 'شنيور-ومفك-(شحن-بطارية)',
    parentId: 98,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 101,
    title: 'شنيور ومفك عزم (شحن بطارية)',
    slug: 'شنيور-ومفك-عزم-(شحن-بطارية)',
    parentId: 98,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 102,
    title: 'مقصات كهربائيه',
    slug: 'مقصات-كهربائيه',
    parentId: null,
    order: 15,
    img: 'http://etoolsshop.com/uploads/images/category/مقص تقليم%20اسيجة.png',
    active: 1,
  },
  {
    id: 103,
    title: 'مقصات صاج ',
    slug: 'مقصات-صاج-',
    parentId: 102,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 104,
    title: 'مقصات الاسفنج',
    slug: 'مقصات-الاسفنج',
    parentId: 102,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 105,
    title: 'منشار صينيه',
    slug: 'منشار-صينيه',
    parentId: 28,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 106,
    title: 'صنفره كهربائيه',
    slug: 'صنفره-كهربائيه',
    parentId: null,
    order: 8,
    img: 'http://etoolsshop.com/uploads/images/category/صنفره%20تردديه.png',
    active: 1,
  },
  {
    id: 107,
    title: 'صنفره تردديه',
    slug: 'صنفره-تردديه',
    parentId: 106,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 108,
    title: 'صنفره دائريه',
    slug: 'صنفره-دائريه',
    parentId: 106,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 109,
    title: 'صنفره دبابه',
    slug: 'صنفره-دبابه',
    parentId: 106,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 111,
    title: 'مواتير',
    slug: 'مواتير',
    parentId: null,
    order: 10,
    img: 'http://etoolsshop.com/uploads/images/category/موتور%20جلخ.png',
    active: 1,
  },
  {
    id: 112,
    title: 'مواتير جلخ',
    slug: 'مواتير-جلخ',
    parentId: 111,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 113,
    title: 'مواتير خلاط',
    slug: 'مواتير-خلاط',
    parentId: 111,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 114,
    title: 'ديسك قطعيه',
    slug: 'ديسك-قطعيه',
    parentId: null,
    order: 11,
    img:
      'http://etoolsshop.com/uploads/images/category/ديسك%20حديد%20ومعدن.png',
    active: 1,
  },
  {
    id: 115,
    title: 'منشار طبليه',
    slug: 'منشار-طبليه',
    parentId: 28,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 116,
    title: 'ديسك  خشب',
    slug: 'ديسك-خشب',
    parentId: 114,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 117,
    title: 'ديسك  خشب و الومينيوم',
    slug: 'ديسك-خشب-و-الومينيوم',
    parentId: 114,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 119,
    title: 'ديسك حديد ومعدن',
    slug: 'ديسك-حديد-ومعدن',
    parentId: 114,
    order: 4,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 124,
    title: 'اكسسوار اجهزة الليزر',
    slug: 'اكسسوار-اجهزة-الليزر',
    parentId: 22,
    order: 8,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 125,
    title: 'ميزان مياه ديجيتال وعادة',
    slug: 'ميزان-مياه-ديجيتال-وعادة',
    parentId: 22,
    order: 4,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 126,
    title: 'اطقم و عدد يدويه',
    slug: 'اطقم-و-عدد-يدويه',
    parentId: null,
    order: 8,
    img: 'http://etoolsshop.com/uploads/images/category/اطقم.png',
    active: 1,
  },
  {
    id: 127,
    title: 'فاره كهربائيه',
    slug: 'فاره-كهربائيه',
    parentId: null,
    order: 9,
    img: 'http://etoolsshop.com/uploads/images/category/فاره-كهربائيه.jpg',
    active: 1,
  },
  {
    id: 130,
    title: 'مسدس شمع',
    slug: 'مسدس-شمع',
    parentId: null,
    order: 19,
    img: 'http://etoolsshop.com/uploads/images/category/مسدس%20شمع.png',
    active: 1,
  },
  {
    id: 132,
    title: 'اسطوانات قطع معدن',
    slug: 'اسطوانات-قطع-معدن',
    parentId: 131,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 133,
    title: 'اسطوانات صينية',
    slug: 'اسطوانات-صينية',
    parentId: 131,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 136,
    title: 'ماكينات نجيله',
    slug: 'ماكينات-نجيله',
    parentId: 18,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 137,
    title: 'مقص اسيجه',
    slug: 'مقص-اسيجه',
    parentId: 18,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 139,
    title: 'بلاور حدائق',
    slug: 'بلاور-حدائق',
    parentId: 18,
    order: 4,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 140,
    title: 'اكسسوارات وملحقات الاجهزه المتعدده',
    slug: 'اكسسوارات-وملحقات-الاجهزه-المتعدده',
    parentId: 24,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 142,
    title: 'منتجات دريميل',
    slug: 'منتجات-دريميل',
    parentId: null,
    order: 24,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 0,
  },
  {
    id: 141,
    title: 'ملحقات دريميل',
    slug: 'ملحقات-دريميل',
    parentId: 142,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 143,
    title: 'معدات دريميل',
    slug: 'معدات-دريميل',
    parentId: 142,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 144,
    title: 'كاتر شحن ',
    slug: 'كاتر-شحن-',
    parentId: 102,
    order: 0,
    img: 'http://etoolsshop.com/uploads/images/category/saf7a-beda.jpg',
    active: 1,
  },
  {
    id: 145,
    title: 'اكسسوارت دريميل',
    slug: 'اكسسوارت-دريميل',
    parentId: 142,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 146,
    title: 'منشار ترددى',
    slug: 'منشار-ترددى',
    parentId: 28,
    order: 0,
    img: 'http://etoolsshop.com/uploads/images/category/WHITE%20PAPER.jpg',
    active: 1,
  },
  {
    id: 147,
    title: 'اجهزة راوتر',
    slug: 'اجهزة-راوتر',
    parentId: null,
    order: 16,
    img: 'http://etoolsshop.com/uploads/images/category/راوتر.png',
    active: 1,
  },
  {
    id: 148,
    title: 'كومبريسور هواء',
    slug: 'كومبريسور-هواء',
    parentId: null,
    order: 25,
    img: 'http://etoolsshop.com/uploads/images/category/كمبريسور.png',
    active: 1,
  },
  {
    id: 149,
    title: 'كوريك ',
    slug: 'كوريك-',
    parentId: null,
    order: 26,
    img: 'http://etoolsshop.com/uploads/images/category/كوريك.png',
    active: 1,
  },
  {
    id: 168,
    title: 'ميثقاب ',
    slug: 'ميثقاب-',
    parentId: null,
    order: 16,
    img: 'http://etoolsshop.com/uploads/images/category/مثقاب1.jpg',
    active: 1,
  },
  {
    id: 150,
    title: 'حامل مثقاب مغناطيسي',
    slug: 'حامل-مثقاب-مغناطيسي',
    parentId: 168,
    order: 5,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 151,
    title: 'صاروخ 4.5',
    slug: 'صاروخ-4.5',
    parentId: 10,
    order: 2,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 152,
    title: 'صاروخ 4 بوصة ',
    slug: 'صاروخ-4-بوصة-',
    parentId: 10,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 153,
    title: 'صاروخ 5 بوصة ',
    slug: 'صاروخ-5-بوصة-',
    parentId: 10,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 154,
    title: 'صاروخ 7 بوصة ',
    slug: 'صاروخ-7-بوصة-',
    parentId: 10,
    order: 4,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 155,
    title: 'صاروخ 9 بوصة',
    slug: 'صاروخ-9-بوصة',
    parentId: 10,
    order: 5,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 157,
    title: 'شنيور خفيف ',
    slug: 'شنيور-خفيف-',
    parentId: 17,
    order: 1,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 158,
    title: 'مفتاح ربط مطرقي هواء ',
    slug: 'مفتاح-ربط-مطرقي-هواء-',
    parentId: 17,
    order: 6,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 159,
    title: 'مفتاح ربط مطرقي كهرباء',
    slug: 'مفتاح-ربط-مطرقي-كهرباء',
    parentId: 17,
    order: 7,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 160,
    title: 'اكسسوار صاروخ ',
    slug: 'اكسسوار-صاروخ-',
    parentId: 10,
    order: 10,
    img: 'http://etoolsshop.com/uploads/images/category/GRIENDER%201.jpg',
    active: 1,
  },
  {
    id: 161,
    title: 'اكسسوار دسك',
    slug: 'اكسسوار-دسك',
    parentId: 114,
    order: 0,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 162,
    title: 'صنفرة سير ',
    slug: 'صنفرة-سير-',
    parentId: 106,
    order: 0,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 163,
    title: 'صنفرة حوائط ',
    slug: 'صنفرة-حوائط-',
    parentId: 106,
    order: 0,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 164,
    title: 'ماكينة لحام',
    slug: 'ماكينة-لحام',
    parentId: null,
    order: 9,
    img: 'http://etoolsshop.com/uploads/images/category/ماكينة%20لحام.jpg',
    active: 1,
  },
  {
    id: 165,
    title: 'كاوية لحام ',
    slug: 'كاوية-لحام-',
    parentId: null,
    order: 13,
    img: 'http://etoolsshop.com/uploads/images/category/كاوية%20اللحام.jpg',
    active: 1,
  },
  {
    id: 166,
    title: 'ميني كرافت ',
    slug: 'ميني-كرافت-',
    parentId: null,
    order: 8,
    img: 'http://etoolsshop.com/uploads/images/category/مينى%20كرافت.jpg',
    active: 1,
  },
  {
    id: 167,
    title: 'مكنسة كهربائية ',
    slug: 'مكنسة-كهربائية-',
    parentId: null,
    order: 15,
    img: 'http://etoolsshop.com/uploads/images/category/مكنسة%20كهربائية.jpg',
    active: 1,
  },
  {
    id: 170,
    title: 'مولدات كهرباء ',
    slug: 'مولدات-كهرباء-',
    parentId: null,
    order: 19,
    img: 'http://etoolsshop.com/uploads/images/category/مولدات%20كهرباء.jpg',
    active: 1,
  },
  {
    id: 171,
    title: 'ماكينات قطع سيراميك ورخام',
    slug: 'ماكينات-قطع-سيراميك-ورخام',
    parentId: null,
    order: 13,
    img:
      'http://etoolsshop.com/uploads/images/category/ماكينات%20قطع%20سيراميك%20ورخام%201.jpg',
    active: 1,
  },
  {
    id: 172,
    title: 'ميزان قامة ',
    slug: 'ميزان-قامة-',
    parentId: 22,
    order: 3,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 173,
    title: 'ماكينة قطع يدوى',
    slug: 'ماكينة-قطع-يدوى',
    parentId: 171,
    order: 22,
    img:
      'http://etoolsshop.com/uploads/images/category/ماكينات%20قطع%20سيراميك%20ورخام%201.jpg',
    active: 1,
  },
  {
    id: 174,
    title: 'ماكينة قطع اتوماتيك',
    slug: 'ماكينة-قطع-اتوماتيك',
    parentId: 171,
    order: 22,
    img:
      'http://etoolsshop.com/uploads/images/category/ماكينات%20قطع%20سيراميك%20ورخام%201.jpg',
    active: 1,
  },
  {
    id: 175,
    title: 'منشار اركيت نماذج',
    slug: 'منشار-اركيت-نماذج',
    parentId: 28,
    order: 0,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
  {
    id: 176,
    title: 'عجلة القياس اليدوية',
    slug: 'عجلة-القياس-اليدوية',
    parentId: 22,
    order: 7,
    img: 'http://etoolsshop.com/uploads/images/category/',
    active: 1,
  },
];
